### ISSUE TITLE
Uncaught TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by extremeblue** [JunSuzukiJapan/atom-keyboard-macros#19]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-keyboard-macros](https://github.com/JunSuzukiJapan/atom-keyboard-macros) package 0.9.2

### Stack Trace

Uncaught TypeError: Cannot read property 'on' of undefined

```
At C:\Users\Administrator\.atom\packages\atom-keyboard-macros\lib\find-and-replace.coffee:127

TypeError: Cannot read property 'on' of undefined
    at FindAndReplace.module.exports.FindAndReplace.addHooks (/packages/atom-keyboard-macros/lib/find-and-replace.coffee:127:22)
    at FindAndReplace.module.exports.FindAndReplace.startRecording (/packages/atom-keyboard-macros/lib/find-and-replace.coffee:103:6)
    at Object.start_kbd_macro (/packages/atom-keyboard-macros/lib/atom-keyboard-macros.coffee:135:11)
    at /packages/atom-keyboard-macros/lib/atom-keyboard-macros.coffee:68:104)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:22.5.0 core:move-up (input.hidden-input)
  3x -0:22.1.0 core:backspace (input.hidden-input)
  2x -0:17.8.0 find-and-replace:toggle (atom-text-editor.editor.is-focused)
     -0:17.7.0 atom-keyboard-macros:start_kbd_macro (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
atom-keyboard-macros 0.9.2 
auto-encoding 0.7.0 
emmet 2.4.3 
export-html 3.1.0 
highlight-selected 0.13.1 
markdown-preview-plus 2.4.9 
minimap 4.27.1 
status-bar-cursor-position 0.8.0 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.1 
vim-mode-plus 0.90.2 
```

**Comment by didiergm** [comment]
This happened to me also 
OS Linux Mint
Atom 1.17.0-Beta5 x64
French keyboard
To reproduce
Start recording : type ctrl+X then (

**Comment by jpjpjp** [comment]
Same here on macOS atom v6.5.0
atom-prism@0.1.3
atom-keyboard-macros@0.9.2
autocomplete-python@1.8.50
browser-plus@0.0.87
file-watcher@1.1.0
kite@0.26.0
linter@1.11.21
linter-jshint@3.0.2
maximize-panes@0.2.0
minimap@4.27.1
move-panes@0.2.0
node-debugger@1.10.1
platformio-ide-terminal@2.2.3
tablr@1.8.3

**Comment by ekortright** [comment]
Just installed version 1.17.2 x64 using Mac .pkg download.  The exception is thrown as soon as you press Ctrl-x ( to start recording.

**Comment by larrywpetersen** [comment]
I am on Windows and it throws the error as soon as I choose Packages -> atom-keyboard-macros -> Start Record.

**Comment by jpluimers** [comment]
Happens on Mac OS X with both:

- menu `Packages` -> `atom-keyboard-macros` -> `Start Record` and 
- keybaord `Ctrl+X` -> `(`.

Stacktrace is indentical in both cases.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [atom-keyboard-macros](https://github.com/JunSuzukiJapan/atom-keyboard-macros) package 0.9.2


### Stack Trace

Uncaught TypeError: Cannot read property 'on' of undefined

```
At /Users/jeroenp/.atom/packages/atom-keyboard-macros/lib/find-and-replace.coffee:127

TypeError: Cannot read property 'on' of undefined
    at FindAndReplace.module.exports.FindAndReplace.addHooks (/packages/atom-keyboard-macros/lib/find-and-replace.coffee:127:22)
    at FindAndReplace.module.exports.FindAndReplace.startRecording (/packages/atom-keyboard-macros/lib/find-and-replace.coffee:103:6)
    at Object.start_kbd_macro (/packages/atom-keyboard-macros/lib/atom-keyboard-macros.coffee:135:11)
    at /packages/atom-keyboard-macros/lib/atom-keyboard-macros.coffee:68:104)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -1:35.9.0 pane:show-previous-item (input.hidden-input)
  3x -1:34.9.0 pane:show-next-item (input.hidden-input)
     -1:31 pane:show-previous-item (input.hidden-input)
     -1:27.8.0 pane:show-next-item (input.hidden-input)
     -1:26.3.0 core:close (input.hidden-input)
     -1:11.3.0 editor:consolidate-selections (input.hidden-input)
     -1:11.3.0 core:cancel (input.hidden-input)
  2x -1:06.8.0 find-and-replace:toggle (atom-text-editor.editor.is-focused)
     -1:06.8.0 atom-keyboard-macros:start_kbd_macro (input.hidden-input)
     -1:06.1.0 core:move-down (input.hidden-input)
     -0:20 settings-view:open (a.btn-issue.btn.btn-error)
     -0:17.4.0 core:close (div.panels-item)
     -0:13.3.0 core:cut (input.hidden-input)
     -0:11.1.0 core:backspace (input.hidden-input)
 57x -0:10.5.0 core:move-right (input.hidden-input)
     -0:07.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-html-preview 0.1.22 
atom-keyboard-macros 0.9.2 
atom-wrap-in-tag 0.6.0 
autocomplete-python 1.9.1 
autocomplete-xml 0.9.4 
broadcast 0.4.0 
busy-signal 1.4.3 
close-tags 0.6.0 
color-picker 2.2.5 
console-panel 0.2.1 
counter 0.3.5 
emmet 2.4.3 
export-html 3.1.0 
file-icons 2.1.8 
git-plus 7.9.3 
intentions 1.1.2 
kite 0.28.1 
language-batch 0.4.0 
language-bbcode 0.1.1 
language-innosetup 2.12.0 
language-pascal 0.20.2 
language-plantuml 0.2.0 
language-restructuredtext 1.1.0 
language-routeros-script 0.2.0 
linter 2.2.0 
linter-ui-default 1.6.2 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.5 
nav-panel 0.0.11 
nav-panel-plus 0.3.0 
omnisharp-atom 0.31.2 
pandoc-convert 1.1.1 
plantuml-preview 0.12.9 
print-atom 0.1.1 
rot13 0.3.0 
rst-preview-pandoc 0.1.12 
sort-lines 0.14.0 
sync-settings 0.8.2 
tabs-to-spaces 1.0.3 
tool-bar-markdown-writer 0.3.0 
xml-formatter 0.11.0 
xml-tools 0.2.1 
```

**Comment by Mavarice** [comment]
Why was this closed? The issue continues to persist on version 1.25 x64
