### ISSUE TITLE
Failed to activate the atom-keyboard-macros package

### ISSUE THREAD

**Issue by jwalters-gpsw** [JunSuzukiJapan/atom-keyboard-macros#28]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-keyboard-macros](https://github.com/JunSuzukiJapan/atom-keyboard-macros) package 0.11.0

### Stack Trace

Failed to activate the atom-keyboard-macros package

```
At Cannot read property 'nodeName' of undefined

TypeError: Cannot read property 'nodeName' of undefined
    at CommandLogger.module.exports.CommandLogger.logCommand (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/command-logger.js:81:44)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/command-logger.js:33:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:26)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at FindAndReplace.module.exports.FindAndReplace.activate (/packages/atom-keyboard-macros/lib/find-and-replace.coffee:30:19)
    at Object.activate (/packages/atom-keyboard-macros/lib/atom-keyboard-macros.coffee:89:11)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:968:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:26)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:05.5.0 atom-keyboard-macros:start_kbd_macro (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-keyboard-macros 0.11.0 
browse 1.7.0 
concourse-vis 1.4.0 
open-in-developer-mode 0.3.0 
open-package 0.2.0 
package-developer-toolbar 0.10.0 
pretty-json 1.6.4 
satisfy-dependencies 0.4.1 
sort-lines 0.14.0 
split-diff 1.5.0 
tool-bar 1.1.0 
```

**Comment by mocho6655697623** [comment]
I had the same problem.
I just uninstalled the package, and reinstalled it.
then, I could solve the problem.
