### ISSUE TITLE
Installing “atom-keyboard-macros@0.12.0” failed

### ISSUE THREAD

**Issue by intersel** [JunSuzukiJapan/atom-keyboard-macros#33]
Hi,

My environment is:
- windows 10
- atom 1.23.3 x64

Trying to install the package via the setting->install, I've got this error:

> 
> Installing “atom-keyboard-macros@0.12.0” failed.Hide output…
> 
> > keyboard-layout@2.0.13 install C:\Users\Emmanuel\AppData\Local\Temp\apm-install-dir-118021-13168-1cczmsc.q9t2ihpvi\node_modules\atom-keyboard-macros\node_modules\keyboard-layout
> > node-gyp rebuild
> 
> 
> C:\Users\Emmanuel\AppData\Local\Temp\apm-install-dir-118021-13168-1cczmsc.q9t2ihpvi\node_modules\atom-keyboard-macros\node_modules\keyboard-layout>if not defined npm_config_node_gyp (node "C:\Users\Emmanuel\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Emmanuel\AppData\Local\atom\app-1.23.3\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
> C:\Users\Emmanuel\AppData\Local\Temp\apm-install-dir-118021-13168-1cczmsc.q9t2ihpvi
> `-- (empty)
> 
> 
> npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
> gyp ERR! configure error 
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> gyp ERR! stack     at failNoPython (C:\Users\Emmanuel\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
> gyp ERR! stack     at C:\Users\Emmanuel\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
> gyp ERR! stack     at C:\Users\Emmanuel\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\graceful-fs\polyfills.js:284:29
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
> gyp ERR! System Windows_NT 10.0.16299
> gyp ERR! command "C:\\Users\\Emmanuel\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Emmanuel\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\Emmanuel\AppData\Local\Temp\apm-install-dir-118021-13168-1cczmsc.q9t2ihpvi\node_modules\atom-keyboard-macros\node_modules\keyboard-layout
> gyp ERR! node -v v6.9.5
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 
> npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Emmanuel\AppData\Local\Temp\apm-install-dir-118021-13168-1cczmsc.q9t2ihpvi\package.json'
> npm WARN apm-install-dir-118021-13168-1cczmsc.q9t2ihpvi No description
> npm WARN apm-install-dir-118021-13168-1cczmsc.q9t2ihpvi No repository field.
> npm WARN apm-install-dir-118021-13168-1cczmsc.q9t2ihpvi No README data
> npm WARN apm-install-dir-118021-13168-1cczmsc.q9t2ihpvi No license field.
> npm ERR! Windows_NT 10.0.16299
> npm ERR! argv "C:\\Users\\Emmanuel\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Emmanuel\\AppData\\Local\\atom\\app-1.23.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Emmanuel\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Emmanuel\\.atom\\.apmrc" "install" "C:\\Users\\Emmanuel\\AppData\\Local\\Temp\\d-118021-13168-1pa12bd.0uwusaif6r\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
> npm ERR! node v6.9.5
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! keyboard-layout@2.0.13 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the keyboard-layout@2.0.13 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the keyboard-layout package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs keyboard-layout
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls keyboard-layout
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\Emmanuel\AppData\Local\Temp\apm-install-dir-118021-13168-1cczmsc.q9t2ihpvi\npm-debug.log
> npm ERR! code 1
>

**Comment by dbdennis** [comment]
Hi. Same problem here, on both linux and mac platforms.  Any hope for fixing this really useful package?

**Comment by VietTralala** [comment]
Same problem here
Ubuntu 17.10
Atom    : 1.25.0-beta2
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 3.6.3
git 2.14.1


> events.js:101 Installing package atom-keyboard-macros failed Error: Installing “atom-keyboard-macros@0.12.1” failed.
>     at /usr/share/atom-beta/resources/app/node_modules/settings-view/lib/package-manager.js:547:27
>     at exit (/usr/share/atom-beta/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
>     at triggerExitCallback (/usr/share/atom-beta/resources/app/src/buffered-process.js:267:15)
>     at bufferStream (/usr/share/atom-beta/resources/app/src/buffered-process.js:288:15)
>     at Socket.stream.on (/usr/share/atom-beta/resources/app/src/buffered-process.js:164:13)
>     at emitOne (events.js:101:20)
>     at Socket.emit (events.js:191:7)
>     at Pipe._handle.close [as _onclose] (net.js:510:12) 
> > keyboard-layout@2.0.13 install /tmp/apm-install-dir-118122-32017-1ewh3dv.dg6dc2fbt9/node_modules/atom-keyboard-macros/node_modules/keyboard-layout
> > node-gyp rebuild
> 
> /tmp/apm-install-dir-118122-32017-1ewh3dv.dg6dc2fbt9
> └── (empty)
> 
> 
> npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
> gyp ERR! configure error 
> gyp ERR! stack Error: Python executable "/usr/share/atom-beta/resources/app/apm/bin/python-interceptor.sh" is v3.6.3, which is not supported by gyp.
> gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
> gyp ERR! stack     at failPythonVersion (/usr/share/atom-beta/resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
> gyp ERR! stack     at /usr/share/atom-beta/resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> gyp ERR! System Linux 4.13.0-32-generic
> gyp ERR! command "/usr/share/atom-beta/resources/app/apm/bin/node" "/usr/share/atom-beta/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
> gyp ERR! cwd /tmp/apm-install-dir-118122-32017-1ewh3dv.dg6dc2fbt9/node_modules/atom-keyboard-macros/node_modules/keyboard-layout
> gyp ERR! node -v v6.9.5
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 
> npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118122-32017-1ewh3dv.dg6dc2fbt9/package.json'
> npm WARN apm-install-dir-118122-32017-1ewh3dv.dg6dc2fbt9 No description
> npm WARN apm-install-dir-118122-32017-1ewh3dv.dg6dc2fbt9 No repository field.
> npm WARN apm-install-dir-118122-32017-1ewh3dv.dg6dc2fbt9 No README data
> npm WARN apm-install-dir-118122-32017-1ewh3dv.dg6dc2fbt9 No license field.
> npm ERR! Linux 4.13.0-32-generic
> npm ERR! argv "/usr/share/atom-beta/resources/app/apm/bin/node" "/usr/share/atom-beta/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/viet/.atom/.apm/.apmrc" "--userconfig" "/home/viet/.atom/.apmrc" "install" "/tmp/d-118122-32017-1g8l5ce.ywwi1thuxr/package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
> npm ERR! node v6.9.5
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! keyboard-layout@2.0.13 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the keyboard-layout@2.0.13 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the keyboard-layout package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs keyboard-layout
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls keyboard-layout
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /tmp/apm-install-dir-118122-32017-1ewh3dv.dg6dc2fbt9/npm-debug.log
> npm ERR! code 1

**Comment by aradove** [comment]
+1 I have the same error.

Installing “atom-keyboard-macros@0.12.1” failed.Hide output…

> keyboard-layout@2.0.13 install /tmp/apm-install-dir-118211-950-1qw0hf2.eayn4uz0k9/node_modules/atom-keyboard-macros/node_modules/keyboard-layout
> node-gyp rebuild

/tmp/apm-install-dir-118211-950-1qw0hf2.eayn4uz0k9
└── (empty)


npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/usr/share/atom/resources/app/apm/bin/python-interceptor.sh" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Linux 4.14.0-041400-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-118211-950-1qw0hf2.eayn4uz0k9/node_modules/atom-keyboard-macros/node_modules/keyboard-layout
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118211-950-1qw0hf2.eayn4uz0k9/package.json'
npm WARN apm-install-dir-118211-950-1qw0hf2.eayn4uz0k9 No description
npm WARN apm-install-dir-118211-950-1qw0hf2.eayn4uz0k9 No repository field.
npm WARN apm-install-dir-118211-950-1qw0hf2.eayn4uz0k9 No README data
npm WARN apm-install-dir-118211-950-1qw0hf2.eayn4uz0k9 No license field.
npm ERR! Linux 4.14.0-041400-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/martin/.atom/.apm/.apmrc" "--userconfig" "/home/martin/.atom/.apmrc" "install" "/tmp/d-118211-950-5dxa7w.kvdpiizfr/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! keyboard-layout@2.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keyboard-layout@2.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keyboard-layout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keyboard-layout
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keyboard-layout
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118211-950-1qw0hf2.eayn4uz0k9/npm-debug.log
npm ERR! code 1

**Comment by audreytoskin** [comment]
On Linux, I noticed that installing the development packages for libxkbfile solved this installation error. On Debian-based systems, you'd want to install `libxkbfile-dev`; on Red Hat-based systems, the package is `libxkbfile-devel`.

On Mac, @haberdashPI noted says "Anaconda is installed in my PATH and its version of c++ was overriding xcode's version. I removed it from my path and installed this from the command line successfully."

See #26

**Comment by stepbeekio** [comment]
@terrycloth Thanks this solved the issue for me on Ubuntu-18.04.

**Comment by Jadiker** [comment]
Any solution yet for Windows?

**Comment by RyoYoshida** [comment]
For Windows.

You must install "node-gyp" on yourself.

1. install node.js
2. install python2.x
3. install https://github.com/felixrieseberg/windows-build-tools
4. npm config set msvs_version 2015
5. npm config set python c:\python27\python.exe
6. npm install -g node-gyp

**Comment by ravigupta-design** [comment]
> On Linux, I noticed that installing the development packages for libxkbfile solved this installation error. On Debian-based systems, you'd want to install `libxkbfile-dev`; on Red Hat-based systems, the package is `libxkbfile-devel`.
> 
> On Mac, @haberdashPI noted says "Anaconda is installed in my PATH and its version of c++ was overriding xcode's version. I removed it from my path and installed this from the command line successfully."
> 
> See #26

This worked for me on xbuntu 18.04
