### ISSUE TITLE
Install failed :(

### ISSUE THREAD

**Issue by Disore** [JunSuzukiJapan/atom-keyboard-macros#37]
I use macOS High Sierra (10.13.6),
My Atom version is 1.30.0,
Trying to install atom-keyboard-macros 0.12.1,
Getting error:

> keyboard-layout@2.0.14 install /private/var/folders/85/rbygs1dd0877nk9c_kx78ykw0000gn/T/apm-install-dir-118823-19895-ze77yk.18bz7aatt9/node_modules/atom-keyboard-macros/node_modules/keyboard-layout
> node-gyp rebuild

/private/var/folders/85/rbygs1dd0877nk9c_kx78ykw0000gn/T/apm-install-dir-118823-19895-ze77yk.18bz7aatt9
`-- (empty)

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/85/rbygs1dd0877nk9c_kx78ykw0000gn/T/apm-install-dir-118823-19895-ze77yk.18bz7aatt9/node_modules/atom-keyboard-macros/node_modules/keyboard-layout
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/85/rbygs1dd0877nk9c_kx78ykw0000gn/T/apm-install-dir-118823-19895-ze77yk.18bz7aatt9/package.json'
npm WARN apm-install-dir-118823-19895-ze77yk.18bz7aatt9 No description
npm WARN apm-install-dir-118823-19895-ze77yk.18bz7aatt9 No repository field.
npm WARN apm-install-dir-118823-19895-ze77yk.18bz7aatt9 No README data
npm WARN apm-install-dir-118823-19895-ze77yk.18bz7aatt9 No license field.
npm ERR! Darwin 17.7.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/ayashin/.atom/.apm/.apmrc" "--userconfig" "/Users/ayashin/.atom/.apmrc" "install" "/private/var/folders/85/rbygs1dd0877nk9c_kx78ykw0000gn/T/d-118823-19895-1ivc0sl.6gklk2csor/package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! keyboard-layout@2.0.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keyboard-layout@2.0.14 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keyboard-layout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keyboard-layout
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keyboard-layout
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/85/rbygs1dd0877nk9c_kx78ykw0000gn/T/apm-install-dir-118823-19895-ze77yk.18bz7aatt9/npm-debug.log
npm ERR! code 1

**Comment by jli** [comment]
I got this too. I think the issue is that you need a full installation of Xcode. This fixed the issue for me:

https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error

Basically, you need to install the full Xcode application and then run:

`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

**Comment by 4gekkman** [comment]
What should I do if I can't install Xcode, because I use Windows?

**Comment by jli** [comment]
> What should I do if I can't install Xcode, because I use Windows?

Sorry, I'm not sure! I think the issue is with the underlying `keyboard-layout` library (I saw some Linux users find a different fix, I think). So maybe look for support related to `keyboard-layout` and Windows?

**Comment by Mipronimo** [comment]
@4gekkman maybe this helps you https://github.com/JunSuzukiJapan/atom-keyboard-macros/issues/33#issuecomment-420492068
