### ISSUE TITLE
Atom package install failed

### ISSUE THREAD

**Issue by skerns00** [JunSuzukiJapan/atom-keyboard-macros#45]
This is what I got when trying to install:

> keyboard-layout@2.0.16 install /tmp/apm-install-dir-119826-5159-1hy4mhg.lb0u/node_modules/atom-keyboard-macros/node_modules/keyboard-layout
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-119826-5159-1hy4mhg.lb0u/node_modules/atom-keyboard-macros/node_modules/keyboard-layout/build'
  CXX(target) Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager.o
make: Leaving directory '/tmp/apm-install-dir-119826-5159-1hy4mhg.lb0u/node_modules/atom-keyboard-macros/node_modules/keyboard-layout/build'

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
In file included from ../src/keyboard-layout-manager.cc:1:
../src/keyboard-layout-manager.h:7:10: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [keyboard-layout-manager.target.mk:104: Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 5.2.0-kali2-amd64
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-119826-5159-1hy4mhg.lb0u/node_modules/atom-keyboard-macros/node_modules/keyboard-layout
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-119826-5159-1hy4mhg.lb0u/package.json'
npm WARN apm-install-dir-119826-5159-1hy4mhg.lb0u No description
npm WARN apm-install-dir-119826-5159-1hy4mhg.lb0u No repository field.
npm WARN apm-install-dir-119826-5159-1hy4mhg.lb0u No README data
npm WARN apm-install-dir-119826-5159-1hy4mhg.lb0u No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keyboard-layout@2.0.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keyboard-layout@2.0.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.atom/.apm/_logs/2019-09-26T20_35_37_852Z-debug.log

**Comment by mattboston** [comment]
I'm getting the same error.  It seems like an abandoned package.  Anyone know how to fix the issue?

**Comment by sigod** [comment]
I get this error:

```
> keyboard-layout@2.0.16 install C:\Users\sigod\AppData\Local\Temp\apm-install-dir-12036-28012-2gqoad.js2to\node_modules\atom-keyboard-macros\node_modules\keyboard-layout
> node-gyp rebuild


C:\Users\sigod\AppData\Local\Temp\apm-install-dir-12036-28012-2gqoad.js2to\node_modules\atom-keyboard-macros\node_modules\keyboard-layout>if not defined npm_config_node_gyp (node "C:\Users\sigod\AppData\Local\atom\app-1.45.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\sigod\AppData\Local\atom\app-1.45.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Users\sigod\AppData\Local\Programs\Python\Python38\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\sigod\AppData\Local\atom\app-1.45.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\sigod\AppData\Local\atom\app-1.45.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\sigod\AppData\Local\atom\app-1.45.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\sigod\\AppData\\Local\\atom\\app-1.45.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\sigod\\AppData\\Local\\atom\\app-1.45.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\sigod\AppData\Local\Temp\apm-install-dir-12036-28012-2gqoad.js2to\node_modules\atom-keyboard-macros\node_modules\keyboard-layout
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\sigod\AppData\Local\Temp\apm-install-dir-12036-28012-2gqoad.js2to\package.json'
npm WARN apm-install-dir-12036-28012-2gqoad.js2to No description
npm WARN apm-install-dir-12036-28012-2gqoad.js2to No repository field.
npm WARN apm-install-dir-12036-28012-2gqoad.js2to No README data
npm WARN apm-install-dir-12036-28012-2gqoad.js2to No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keyboard-layout@2.0.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keyboard-layout@2.0.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sigod\.atom\.apm\_logs\2020-04-06T01_47_53_423Z-debug.log
```

**Comment by albert200000** [comment]
For me installing libxkbfile-devel system package fixed the error on Solus linux. On Ubuntu its name is libxkbfile-dev.
