### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by ajman098** [JunSuzukiJapan/atom-keyboard-macros#46]
Also having trouble installing this package. Linux Mint 19.3 Cin. I have verified that I have gcc and libxkbfile-dev installed.

```
Installing atom-keyboard-macros to /home/ajman/.atom/packages ✗

> keyboard-layout@2.0.16 install /tmp/apm-install-dir-120422-7181-w7ijp6.tsl4/node_modules/atom-keyboard-macros/node_modules/keyboard-layout
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-120422-7181-w7ijp6.tsl4/node_modules/atom-keyboard-macros/node_modules/keyboard-layout/build'
  CXX(target) Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager.o
keyboard-layout-manager.target.mk:104: recipe for target 'Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager.o' failed
make: Leaving directory '/tmp/apm-install-dir-120422-7181-w7ijp6.tsl4/node_modules/atom-keyboard-macros/node_modules/keyboard-layout/build'

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
make: g++: Command not found
make: *** [Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 5.3.0-46-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-120422-7181-w7ijp6.tsl4/node_modules/atom-keyboard-macros/node_modules/keyboard-layout
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-120422-7181-w7ijp6.tsl4/package.json'
npm WARN apm-install-dir-120422-7181-w7ijp6.tsl4 No description
npm WARN apm-install-dir-120422-7181-w7ijp6.tsl4 No repository field.
npm WARN apm-install-dir-120422-7181-w7ijp6.tsl4 No README data
npm WARN apm-install-dir-120422-7181-w7ijp6.tsl4 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keyboard-layout@2.0.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keyboard-layout@2.0.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ajman/.atom/.apm/_logs/2020-05-22T15_46_00_062Z-debug.log
```

**Comment by nandordena** [comment]
me too
