### ISSUE TITLE
Unable to execute N times

### ISSUE THREAD

**Issue by shouya** [JunSuzukiJapan/atom-keyboard-macros#6]
Keyboard macro recorded via <kbd>C-x</kbd><kbd>(</kbd><kbd>C-j</kbd><kbd>C-x</kbd><kbd>)</kbd>, then:

`C-x C-e`

throws the exception. `C-x e` works fine.

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-keyboard-macros](https://github.com/JunSuzukiJapan/atom-keyboard-macros) package, v0.8.2
### Stack Trace

Uncaught TypeError: this.repeatCountView.focus is not a function

```
At /Users/shou/.atom/packages/atom-keyboard-macros/lib/atom-keyboard-macros.coffee:362

TypeError: this.repeatCountView.focus is not a function
    at Object.module.exports.AtomKeyboardMacros.repeat_last_kbd_macro (/Users/shou/.atom/packages/atom-keyboard-macros/lib/atom-keyboard-macros.coffee:362:22)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-keyboard-macros:repeat_last_kbd_macro (/Users/shou/.atom/packages/atom-keyboard-macros/lib/atom-keyboard-macros.coffee:71:110)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:10.9.0 core:move-up (atom-text-editor.editor.emacs-plus.is-focused)
  4x -1:09.7.0 atom-keyboard-macros:repeat_last_kbd_macro (atom-text-editor.editor.emacs-plus.is-focused)
     -1:08.2.0 pane:show-next-item (atom-text-editor.editor.emacs-plus.is-focused)
     -1:05.4.0 core:cancel (input.)
     -0:40.8.0 pane:show-previous-item (div.package-detail.panels-item)
  2x -0:39.8.0 core:move-up (atom-text-editor.editor.emacs-plus.is-focused)
     -0:39.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.emacs-plus.is-focused)
     -0:34.5.0 atom-keyboard-macros:call_last_kbd_macro (atom-text-editor.editor.emacs-plus.is-focused)
  2x -0:34.5.0 find-and-replace:toggle (atom-text-editor.editor.emacs-plus.is-focused)
     -0:34.5.0 core:move-down (atom-text-editor.editor.emacs-plus.is-focused)
     -0:33.1.0 atom-keyboard-macros:call_last_kbd_macro (atom-text-editor.editor.emacs-plus.is-focused)
     -0:33.1.0 core:move-down (atom-text-editor.editor.emacs-plus.is-focused)
     -0:32.3.0 atom-keyboard-macros:repeat_last_kbd_macro (atom-text-editor.editor.emacs-plus.is-focused)
  3x -0:29.6.0 pane:show-next-item (button.)
     -0:03.2.0 core:cancel (input.)
     -0:01.0 atom-keyboard-macros:repeat_last_kbd_macro (input.)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "line-ending-selector",
      "browser-plus",
      "latex",
      "fancy-bracket-matcher",
      "atom-bracket-highlight"
    ],
    "packagesWithKeymapsDisabled": [],
    "projectHome": "/Users/shou/project",
    "themes": [
      "yosemate-ui",
      "atom-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
animated-page-scroll, v1.0.0
atom-keyboard-macros, v0.8.2
clip-history, v0.1.12
emacs-plus, v0.9.12
language-latex, v0.6.1
latex-autocomplete, v0.3.1
minimap, v4.20.0
yosemate-ui, v0.7.1

# Dev
No dev packages
```

**Comment by JunSuzukiJapan** [comment]
I fixed it.
Try v0.8.3, please.

thanks.

**Comment by shouya** [comment]
Fix confirmed, thanks.
